# ------------------------------------------------
# -------------------- Spring --------------------
# ------------------------------------------------
spring:
  application.name: ops-lg-drivers-service
  jackson.serialization.indent_output: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yms
    username: eam
    password: eam
  flyway:
    locations: filesystem:src/main/resources/migrations
    out-of-order: true
  jackson:
    property-naming-strategy: SNAKE_CASE

# ------------------------------------------------
# ---------------- Resilience4j ------------------
# ------------------------------------------------
resilience4j:
  configs:
    default:
      cancelRunningFuture: false
      timeoutDuration: 2s
  instances:
    clientOrder:
      baseConfig: default
    purchaseOrder:
      baseConfig: default
    frubanaClient:
      baseConfig: default
    wmsClient:
      baseConfig: default
    sanitationService:
      baseConfig: default
    returnsService:
      baseConfig: default

# ------------------------------------------------
# ---------------- Resilience4j ------------------
# ------------- Circuit Breaker Conf -------------
# ------------------------------------------------
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - java.lang.IllegalArgumentException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    clientOrder:
      baseConfig: default
    purchaseOrder:
      baseConfig: default
    inventory:
      baseConfig: default
    sanitationService:
      baseConfig: default
    returnsService:
      baseConfig: default

# ------------------------------------------------
# ---------------- Resilience4j ------------------
# ----------------- Retry Conf -------------------
# ------------------------------------------------

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 5000
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - java.lang.IllegalArgumentException
  instances:
    frubanaClient:
      baseConfig: default
    wmsClient:
      baseConfig: default
    financeConciliationOrderRestClient:
      baseConfig: default

# ------------------------------------------------
# ----------- Logs Configuration -----------------
# ------------- Logging Config -------------------
# ------------------------------------------------

log:
  slack:
    uri: https://hooks.slack.com/